contactform:
  description: I'm here to help and answer any question you might have. I look
    forward to hearing from you. Fill out the form and we’ll be in touch as soon
    as possible.
  emailconfig: https://formspree.io/mbjzwagy
facts:
  experience: 1
  projects: 2
  customers: 1
keywords: portfolio, website, netlify, jekyll, keyur, patel, keyurpatel,
  bhutkeyur, bhut_keyur, bhut
author:
  resumelink: /assets/uploads/resume.pdf
  name: Keyur Patel
  cvlink: /assets/uploads/404.html
  phone: +91 799 023 3030
  first: Keyur
  address: Gujarat, IN
  last: Patel
  dob: 13 Jun 2002
  passion: Student, Software Engineer, Web Developer, Graphic Designer
  languages: English, Gujarati, Hindi
  image: /assets/uploads/keyur.jpg
  nationality: INDIAN
  email: keyurbhut12345@gmail.com
  description: Hello, I am an upcoming graduate offering a strong foundation in
    software engineering and programming principles across multiple projects. I
    quickly learn and master new technologies. I have excellent verbal and
    written communication skills. Additionally, I have passion for keeping
    up-to-date with latest development in the IT field. Seeking an opportunity
    to use my knowledge to serve the society.
social:
  facebook: bhutkeyur123
  github: bhutkeyur
  instagram: bhut_keyur
  linkedin: bhutkeyur
  twitter: bhut_keyur
  website: https://keyurbhut.tech/
collections:
  portfolio:
    output: true
title: Keyur Patel
description: My Portfolio Website
baseurl: ""
