service:
  - order: "01"
    name: Web Development
    description: |-
      ⦿ Client Oriented Service
      ⦿ Intrigue your Visitors
      ⦿ SEO Friendly
      ⦿ Customized to suit specific needs
      ⦿ Packages to suit every pocket
      ⦿ Excellent support and free maintenance service
  - order: "02"
    name: Web Design
    description: |-
      ⦿ Flexible & Innovative Solution
      ⦿ Designs that Intrigue your Visitors
      ⦿ One Stop Solution
      ⦿ Customized to suit specific needs
      ⦿ Packages to suit every pocket
      ⦿ Excellent support and free maintenance service
  - order: "03"
    name: Graphic Designing
    description: |-
      ⦿ Business Card Design
      ⦿ Logo Design
      ⦿ Flyer Design
      ⦿ Stationery Design
      ⦿ Merchandize Design
  - order: "04"
    name: Digital Marketing
    description: |-
      ⦿ 360° Analysis
      ⦿ Competitor Analysis
      ⦿ Conversion Monitoring
      ⦿ On/Off-page Optimization
      ⦿ Trend Analysis
      ⦿ Social Engagement
